### ISSUE TITLE
Conj talk

### ISSUE THREAD

**Issue by devn** [rbrush/clara-tools#1]
Hello,

The demo you showed at Clojure/conj was interesting, being able to inspect rules and sessions. Will any of that work make it into `clara-tools`?

Thanks,
Devin

**Comment by rbrush** [comment]
Everything I showed at Strangeloop is in either clara-tools or the clara-rules project. The UI in clara-tools hasn't gone beyond a prototype, since more focus has been on the core project and unrelated projects. (The code is definitely rough since this is a proof of concept and I'm not much of web developer. ;)

For some simple explanation and exploration in the repl, I usually use the clara.tools.inspect and clara.tools.tracing namspaces that come in the core clara-rules project. It doesn't offer a nice UI but can help explain or debug rules in an interactive session.

**Comment by devn** [comment]
Hi Ryan,

Forgive me, when toying with the UI I was trying to left click when I should have been using right click on nodes. It was for this reason that I assumed there might be something unreleased.

FWIW, I'm interested in contributing. It looks like `:test` is unaccounted for right now in the UI, for starters.

In general though, I'd be interested in having a higher level conversation about what direction you'd be interested in seeing the current UI take, what sorts of issues need to be solved, etc.

Thanks,
Devin

**Comment by rbrush** [comment]
Hey Devin, would you be willing to post the UI discussion over at the
Google group (linked below) so we could have the conversation there? There
might be interest in this topic from others (either now or in the future),
so I'd like to have discuss in a forum that is more easily found than in a
github bug.

Thanks,
Ryan

https://groups.google.com/forum/#!forum/clara-rules

**Comment by devn** [comment]
Ah, yes of course. I forgot about the group you created.

Thanks for the reply, will continue the discussion there.
