### ISSUE TITLE
Current status of 0.2 branch

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-tools#9]
It isn't an immediate concern, since I don't plan to work on it immediately, but I was wondering if you could give a brief rundown of the current state of the 0.2 branch, what you want to add before a 0.2 release, etc.  I have other priorities right now (such as performance of clara-rules itself and some internal initiatives), but longer term explainability of rules is something that's been weighing on my mind, and it would be nice to know what the status of this project is.  No rush.

**Comment by rbrush** [comment]
I had tabled 0.2 because other needs took precedence, but it's not far from a merge to master. I hadn't seen a ton of interest in this, but if there is then I'm happy to get this cleaned up and merged, getting it to a better spot for anyone else that wants to work on it.

I'd love to get this to a state where we can crack open an arbitrary session and see what's going on there, or embed this in other web apps as a "developer mode" to troubleshoot issues.

**Comment by WilliamParker** [comment]
If you could clean it up for a merge without too much trouble that would probably be helpful.  My general thought pattern here is that while it isn't our most pressing priority, explainability of outputs is a significant shortcoming in our applications, in which the use of Clara is increasing.  Some efforts to improve this would be internal, but clara-tools might have a place there in the long run.  For now, I've just been reading through the existing code and using it on the simple rules in clara-examples.  

Some particular interests of mine are 
- Stress-testing against large and complicated rulesets, partly for performance but also for the overall user experience including the appearance of the fact explanation graph (so far I've just used this against the relatively simple rulesets in clara-examples).  In some cases we have internal platform things we might want to filter out as well, so I'd have to see how that would work.
- What the user experience would be like for someone in a support analyst sort of role who might be technical (i.e. able to read rules), but to a lesser degree than a software developer.

**Comment by devn** [comment]
@WilliamParker Your second bullet point is what I'm interested in, and frankly, it could even be of some use during development. It would be nice if there were a way for us to tag specific rules to show up in the UI. It would also be nice to trace a particular fact through the system, showing both the rules which fired that led to the insertion of the fact, and the places the fact is subsequently used on the LHS of other rules.

@rbrush Yes, pretty please on getting it ready to merge. Last time I tried to get this working I believe that I had trouble with the visualization of :test, :exists, and possibly accumulators, but it's been awhile.

**Comment by rbrush** [comment]
Alright, basic flows are working with 0.2 dev and I added a minimal example of how to use it to the README, and went ahead and merged into master. (Since this project, and the previous master was experimental, I think it's okay to move things that are still pretty raw.)

I have not addressed the other asks above, but at least we can work towards them in master now. I might suggest logging issues with more details so we can track on them.

This project will probably just be a part-time hobby for me, but I'm happy to help out.

**Comment by WilliamParker** [comment]
Thanks!  For my part, I wasn't so much suggesting particular changes with my points above as just mentioning things on my mind with this project.  I'll try this with some more realistic data/rules (rather than clara-examples) to see how it holds up and go from there, although like you any work here will likely be a side project for me as well.

**Comment by WilliamParker** [comment]
Is there anything else anyone wants to discuss in the context of this issue?  From my standpoint this issue can be closed.

**Comment by rbrush** [comment]
Yeah, this is done so I'm closing it. We can open other issues for anything else that comes up.
